import java.util.*

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6/userguide/multi_project_builds.html
 */

rootProject.name = "MAStaff"
include("MAStaff-API")
include("MAStaff-Bukkit")
include("MAStaff-Bungee")
include("MAStaff-Legacy")

include("MAStaff-Vanish")
include("MAStaff-Glow")
include("MAStaff-PAPI")
include("MAStaff-Velocity")
include("MAStaff-Common")
include("MAStaff-Lite")

include("MAStaff-API:API-Publish")
findProject(":MAStaff-API:API-Publish")?.name = "API-Publish"

// Disabled for now
// include("MAStaff-Punishments")
// include("MAStaff-Punishments:Punishments-Bukkit")
// findProject(":MAStaff-Punishments:Punishments-Bukkit")?.name = "Punishments-Bukkit"
// include("MAStaff-Punishments:Punishments-Bungee")
// findProject(":MAStaff-Punishments:Punishments-Bungee")?.name = "Punishments-Bungee"
// include("MAStaff-Punishments:Punishments-API")
// findProject(":MAStaff-Punishments:Punishments-API")?.name = "Punishments-API"
// findProject(":MAStaff-Punishments:Punishments-Velocity")?.name = "Punishments-Velocity"
// include("MAStaff-Punishments:Punishments-Velocity")

val MASTAFF_NMS = System.getenv("MASTAFF_NMS")?: "false"

if (MASTAFF_NMS.toBoolean()) {
  include("MAStaff-NMS")
  include("MAStaff-NMS:NMS-1.20.1_R0")
  findProject(":MAStaff-NMS:NMS-1.20.1_R0")?.name = "NMS-1.20.1_R0"
  include("MAStaff-NMS:NMS-1.19.4_R0")
  findProject(":MAStaff-NMS:NMS-1.19.4_R0")?.name = "NMS-1.19.4_R0"
  include("MAStaff-NMS:NMS-1.18.2_R0")
  findProject(":MAStaff-NMS:NMS-1.18.2_R0")?.name = "NMS-1.18.2_R0"
  include("MAStaff-NMS:NMS-1.17.1_R0")
  findProject(":MAStaff-NMS:NMS-1.17.1_R0")?.name = "NMS-1.17.1_R0"
  include("MAStaff-NMS:NMS-1.16.5_R0")
  findProject(":MAStaff-NMS:NMS-1.16.5_R0")?.name = "NMS-1.16.5_R0"
  include("MAStaff-NMS:NMS-1.12.2_R0")
  findProject(":MAStaff-NMS:NMS-1.12.2_R0")?.name = "NMS-1.12.2_R0"
  include("MAStaff-NMS:NMS-1.8.8_R0")
  findProject(":MAStaff-NMS:NMS-1.8.8_R0")?.name = "NMS-1.8.8_R0"
  include("MAStaff-NMS:NMS-1.20.2_R0")
  findProject(":MAStaff-NMS:NMS-1.20.2_R0")?.name = "NMS-1.20.2_R0"
}
