#  ███▄ ▄███▓ ▄▄▄        ██████ ▄▄▄█████▓ ▄████▄   ▒█████   ██▀███  ▓█████
# ▓██▒▀█▀ ██▒▒████▄    ▒██    ▒ ▓  ██▒ ▓▒▒██▀ ▀█  ▒██▒  ██▒▓██ ▒ ██▒▓█   ▀
# ▓██    ▓██░▒██  ▀█▄  ░ ▓██▄   ▒ ▓██░ ▒░▒▓█    ▄ ▒██░  ██▒▓██ ░▄█ ▒▒███
# ▒██    ▒██ ░██▄▄▄▄██   ▒   ██▒░ ▓██▓ ░ ▒▓▓▄ ▄██▒▒██   ██░▒██▀▀█▄  ▒▓█  ▄
# ▒██▒   ░██▒ ▓█   ▓██▒▒██████▒▒  ▒██▒ ░ ▒ ▓███▀ ░░ ████▓▒░░██▓ ▒██▒░▒████▒
# ░ ▒░   ░  ░ ▒▒   ▓▒█░▒ ▒▓▒ ▒ ░  ▒ ░░   ░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒▓ ░▒▓░░░ ▒░ ░
# ░  ░      ░  ▒   ▒▒ ░░ ░▒  ░ ░    ░      ░  ▒     ░ ▒ ▒░   ░▒ ░ ▒░ ░ ░  ░
# ░      ░     ░   ▒   ░  ░  ░    ░      ░        ░ ░ ░ ▒    ░░   ░    ░
#        ░         ░  ░      ░           ░ ░          ░ ░     ░        ░  ░
#                                        ░
#
# This is the Config file por MASTCore,
# where you can modify and customize the plugin.
#
# Remember to join my Discord server if you need help:
# https://discord.angelillo15.es/
#
Config:
  language: "english.yml"