#
#  ███▄ ▄███▓ ▄▄▄        ██████ ▄▄▄█████▓ ▄▄▄        █████▒ █████▒
#  ▓██▒▀█▀ ██▒▒████▄    ▒██    ▒ ▓  ██▒ ▓▒▒████▄    ▓██   ▒▓██   ▒
#  ▓██    ▓██░▒██  ▀█▄  ░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄  ▒████ ░▒████ ░
#  ▒██    ▒██ ░██▄▄▄▄██   ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██ ░▓█▒  ░░▓█▒  ░
#  ▒██▒   ░██▒ ▓█   ▓██▒▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒░▒█░   ░▒█░
#  ░ ▒░   ░  ░ ▒▒   ▓▒█░▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░ ▒ ░    ▒ ░
#  ░  ░      ░  ▒   ▒▒ ░░ ░▒  ░ ░    ░      ▒   ▒▒ ░ ░      ░
#  ░      ░     ░   ▒   ░  ░  ░    ░        ░   ▒    ░ ░    ░ ░
#  ░         ░  ░      ░                 ░  ░
#
# This is the Config file for MAStaff Spigot,
# where you can modify and customize the plugin.
#
# Some features are only available on MAStaff Premium
# You can buy it in this places:
# - https://builtbybit.com/resources/25460/
# - https://www.spigotmc.org/resources/105713/
# - https://polymart.org/resource/3051
#
# Remember to join my Discord server if you need help:
# https://discord.nookure.com/
#
# General configuration for the plugin.
#
Config:
  # The language file you want to use for the plugin messages.
  # Included locales: english.yml and spanish.yml
  language: "english.yml"
  # Enable or disable the debug mode.
  # If enabled, the plugin will send more information about the plugin status.
  debug: false
  # Teleport to the previous location when the player leaves the staff mode.
  teleportBack: true
  # Disable the staff mode on exit.
  disableStaffModeOnExit: false
  # Silent chest opening.
  silentChestOpening: true
  # Execute commands on staff mode enter.
  executeCommandsOnEnter: false
  # Execute commands on staff mode exit.
  executeCommandsOnExit: false
  # Commands to execute on staff mode enter.
  # They will be executed as the player
  # when all Staff enable Actions has finished.
  commandsOnEnter:
    - "vanish"
  # Commands to execute on staff mode exit.
  # They will be executed as the player
  # when all Staff enable Actions has finished.
  commandsOnExit:
    - "vanish"
# Here you can configure the plugin addons.
Addons:
  # Enable or disable the Vanish addon.
  vanish: true
  # Enable or disable the freeze feature.
  freeze: true
  # Glow module for the plugin.
  # This is only available for MAStaff Premium version
  # If you have the NEZNAMY TAB plugin, you have to set up some things.
  # Read this wiki page for more information:
  glow: true
# Staff Vault configuration for the plugin.
#
# The staff vault is a virtual chest where the items
# that the player gets when they are in staff mode are stored.
#
StaffVault:
  # enable or disable the staff vault.
  enabled: true
  # Inventory name for the staff vault.
  name: "&8&lStaff Vault"
  # How often does the plugin have to check the inventory?
  # The value is in seconds.
  checkTime: 20
# Freeze section
Freeze:
  # Execute a command when the player is frozen and he or she
  # exits of the servers.
  # This is only available for MAStaff Premium version
  executeCommandOnExit: true
  # Ask the staff member if he or she wants to execute the commands.
  # This is only available for MAStaff Premium version
  askToExecuteCommands: true
  # Commands to execute
  # They will be executed as the console.
  # You can use the following placeholders:
  # ↳ {player} - Player name
  # ↳ {staff} - Staff member name
  # If you want the command to be executed as bungee console, add a "bungee:" prefix.
  commands:
    - "ban {player} &cYou have been perm-banned for leaving the server while you were frozen."
#
# Database configuration for the plugin. With the Bungee version, you must use MariaDB or MySQL.
#
Database:
  # The type of database you want to use, you can choose between SQLite or MySQL.
  # The MySQL driver also works with MariaDB
  # The free version only has SQLite
  type: 'SQLite'
  # Your database host IP address.
  host: '127.0.0.1'
  # Your database host connection port. Default for MariaDB and MySQL is 3306.
  port: 3306
  # Name of your database. A database server can contain multiple databases.
  database: 'mastaff'
  # Your database host username.
  user: 'mastaff'
  # Your database host password.
  password: 'mastaff'