#
#  ███▄ ▄███▓ ▄▄▄        ██████ ▄▄▄█████▓ ▄▄▄        █████▒ █████▒
#  ▓██▒▀█▀ ██▒▒████▄    ▒██    ▒ ▓  ██▒ ▓▒▒████▄    ▓██   ▒▓██   ▒
#  ▓██    ▓██░▒██  ▀█▄  ░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄  ▒████ ░▒████ ░
#  ▒██    ▒██ ░██▄▄▄▄██   ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██ ░▓█▒  ░░▓█▒  ░
#  ▒██▒   ░██▒ ▓█   ▓██▒▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒░▒█░   ░▒█░
#  ░ ▒░   ░  ░ ▒▒   ▓▒█░▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░ ▒ ░    ▒ ░
#  ░  ░      ░  ▒   ▒▒ ░░ ░▒  ░ ░    ░      ▒   ▒▒ ░ ░      ░
#  ░      ░     ░   ▒   ░  ░  ░    ░        ░   ▒    ░ ░    ░ ░
#  ░         ░  ░      ░                 ░  ░
#
# This is the Config file for MAStaff Common (BungeeCord, Spigot, Velocity)
# where you can modify and customize the plugin.
#
# Remember to join my Discord server if you need help:
# https://discord.nookure.com/
#
# General configuration for the plugin.
#
Config:
  # The language file you want to use for the plugin messages.
  # Included locales: english.yml and spanish.yml
  language: "en.yml"
# StaffChat module configuration.
StaffChat:
  # Enable/disable the StaffChat module.
  enabled: true
  # Config for the StaffChat prefix configuration.
  # The prefix is the character that will be used at the
  # beginning of the message to send it to the StaffChat.
  # In velocity proxies, in order to modify the chat messages
  # in server version 1.19.1 or higher, you must use a plugin like
  # Signed Velocity -> https://modrinth.com/plugin/signedvelocity
  # UnSigned Velocity -> https://modrinth.com/plugin/unsignedvelocity
  # I recommend using Signed Velocity because it solves synchronization problems.
  prefix:
    # Enable/disable the prefix for the StaffChat messages.
    enabled: true
    # The prefix for the StaffChat messages.
    key: "#"
# Config for the Helpop module.
Helpop:
  # Enable/disable the Helpop module.
  enabled: true
  # Config for the Helpop cooldown.
  cooldown:
    # Enable/disable the Helpop cooldown.
    enabled: true
    # The time in seconds that the player must wait to send another Helpop message.
    time: 30