name: Publish to nexus

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant perms to gradlew
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew shadowJar
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://repo.nookure.com/
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=es.angelillo15 artifactId=mast-api version=2.0.0b
          assets: extension=jar
          filename: ./MAStaff-API/build/libs/MAStaff-API.jar
