#
#  ███▄ ▄███▓ ▄▄▄        ██████ ▄▄▄█████▓ ▄▄▄        █████▒ █████▒
#  ▓██▒▀█▀ ██▒▒████▄    ▒██    ▒ ▓  ██▒ ▓▒▒████▄    ▓██   ▒▓██   ▒
#  ▓██    ▓██░▒██  ▀█▄  ░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄  ▒████ ░▒████ ░
#  ▒██    ▒██ ░██▄▄▄▄██   ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██ ░▓█▒  ░░▓█▒  ░
#  ▒██▒   ░██▒ ▓█   ▓██▒▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒░▒█░   ░▒█░
#  ░ ▒░   ░  ░ ▒▒   ▓▒█░▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░ ▒ ░    ▒ ░
#  ░  ░      ░  ▒   ▒▒ ░░ ░▒  ░ ░    ░      ▒   ▒▒ ░ ░      ░
#  ░      ░     ░   ▒   ░  ░  ░    ░        ░   ▒    ░ ░    ░ ░
#  ░         ░  ░      ░                 ░  ░
#
# This is the Config file for MAStaff Bungee,
# where you can modify and customize the plugin.
#
# Remember to join my Discord server if you need help:
# https://discord.nookure.com/
#
# General configuration for the plugin.
#
Config:
  # The language file you want to use for the plugin messages.
  # Included locales: english.yml and spanish.yml
  language: "english.yml"
  # Enable or disable the debug mode.
  # If enabled, the plugin will send more information about the plugin status.
  debug: false
  # Date format for the plugin.
  date-format: "dd/MM/yyyy HH:mm:ss"
Modules:
  # Enable or disable the Punishments module.
  # WARNING - This module isn't finished yet.
  #           It's recommended to disable it.
  #           Is only available for MAStaff Bungee (for the moment).
  #           Is in an open beta, so it can have bugs.
  #           If you find any bug, please report it in the GitHub repository
  #           or in the Discord server https://discord.nookure.com.
  punishments: false
Helpop:
  # Cooldown in seconds
  cooldown: 30
#
# Server synchronization configuration for the plugin.
# This is used to synchronize the staff mode between bungeecord servers.
# If you don't want to use this feature, you can disable it.
# This feature requires a Redis server and Redis Bungee.
#
Redis:
  # Enable or disable the Redis synchronization.
  enabled: false
  # The host of your Redis server.
  host: "localhost"
  # The port of your Redis server.
  port: 6379
  # The password of your Redis server.
  password: ""
  # The database of your Redis server.
  database: 0
  # The timeout of your Redis server.
  timeout: 2000
  # The pool size of your Redis server.
  poolSize: 8
  # The prefix of your Redis server.
  prefix: "MAStaff"
  # The channel of your Redis server.
  channel: "MAStaff"
  # Identify the server.
  serverID: "p1"
Database:
  # The type of database you want to use, you can choose between SQLite or MySQL.
  # The MySQL driver also works with MariaDB
  type: 'SQLite'
  # Your database host IP address.
  host: '127.0.0.1'
  # Your database host connection port. Default for MariaDB and MySQL is 3306.
  port: 3306
  # Name of your database. A database server can contain multiple databases.
  database: 'mastaff'
  # Your database host username.
  user: 'mastaff'
  # Your database host password.
  password: 'mastaff'